### ISSUE TITLE
Long distance routes, error with empty "end-time" field

### ISSUE THREAD

**Issue by sysmaker** [PGWelch/com.opendoorlogistics#40]
Hi everyone!

Please help me to solve this issue: when I work with many days duration routes, I don't set "end-time" (or "start-time") in VehicleTypes and get error message (for example):

"Invalid time window record in table VehicleTypes on row 3, either start time or end time is empty but not both.
Component com.opendoorlogistics.components.jsprit threw an exception.
Could not complete operation "myexample.odlx".
Execution of the operation failed."

But when I clear "end-time" and "start-time", the system works and outputs results on the assumption of "start-time" is 0:00.

Previously thanks for explanation, how use ODL Studio for long distance routes (more then one day).

Regards,
Alex.

**Comment by PGWelch** [comment]
Can you post some example rows from your VehicleTypes table?

**Comment by sysmaker** [comment]
Thank you for reply!

The initial problem is at the first screenshot.

![p1](https://cloud.githubusercontent.com/assets/4729358/22320017/53921248-e399-11e6-91b2-d8188f70318e.png)

But, yesterday, I've found solution for my task (it's at second screenshot).

![p2](https://cloud.githubusercontent.com/assets/4729358/22320025/6ce5f2be-e399-11e6-899b-fa59cb46c390.png)

ODL Studio is the cool tool!
